# Use a imagem base com PHP 8.1 e Apache
FROM php:8.1-apache

# Instale os pacotes necessários para o Laravel
RUN apt-get update && \
    apt-get install -y \
        git \
        zip \
        unzip \
        libpq-dev \
        libxml2-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libonig-dev \
        libzip-dev \
        && docker-php-ext-configure gd --with-freetype --with-jpeg \
        && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql pdo_pgsql zip

# Habilitar mod_rewrite do Apache
RUN a2enmod rewrite

# Define o diretório de trabalho como /var/www/html
WORKDIR /var/www/html

# Instale o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Clone o projeto Laravel (substitua o URL pelo seu repositório)
RUN git clone https://github.com/laravel/laravel.git .

# Instale as dependências do Laravel
RUN composer install

# Exponha a porta 80 do Apache
EXPOSE 80

# Defina as variáveis de ambiente necessárias para o Laravel
ENV APP_ENV=production
ENV APP_KEY=SomeRandomString
ENV DB_CONNECTION=sqlsrv
ENV DB_HOST=seu-host
ENV DB_PORT=1433
ENV DB_DATABASE=seu-banco
ENV DB_USERNAME=seu-usuario
ENV DB_PASSWORD=sua-senha

# Copie o script de inicialização do Laravel para o diretório raiz do contêiner
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Execute o Apache em primeiro plano ao iniciar o contêiner
CMD ["/start.sh"]
